server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_record?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    port: 6379
    host: localhost
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true

helper:
  api-test:
    enabled: true
    base-path: /api-test
  hibiscus: com.example
hibiscus:
 helper:
  api-test:
    enabled: true
    base-path: /api-test
  scanPath: com.example
 jwt:
  secret: aGliaXNjdXMtY2V0aWRlLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9u
  expiration: 86400000  # 24小时，单位：毫秒
 cache:
   instances:
    product_cache:
     max-size: 10000
     ttl: 3600000
     eviction-policy: LRU
     compression-enabled: false
     metrics-enabled: false
    user_cache:
     max-size: 5000
     ttl: 7200000
     eviction-policy: LRU
     compression-enabled: true
     metrics-enabled: true
    config_cache:
     max-size: 1000
     ttl: -1
     eviction-policy: LRU
     compression-enabled: false
     metrics-enabled: true
 ssh:
   connection-timeout: 30000
   channel-timeout: 30000
   strict-host-key-checking: false
   default-terminal-type: xterm
   default-cols: 80
   default-rows: 24
 auth:
   admins:
     - username: admin
       password: password
     - username: dev
       password: dev123
